# -*- coding: UTF-8 -*-
# Androguard is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Androguard is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Androguard.  If not, see <http://www。gnu。org/licenses/>。

# frameworks/base/core/res/AndroidManifest.xml
########################################## PERMISSIONS ########################################################
DVM_PERMISSIONS = {
    "MANIFEST_PERMISSION" : {
		"SEND_SMS" : [ "危险" , "发送短信" , "允许应用程序发送短信。恶意程序会在用户未知的情况下发送短信造成损失。" ],
    "SEND_SMS_NO_CONFIRMATION" : [ "危险", "直接发送短信", "在用户未知的情况下直接发送短信。" ],
    "CALL_PHONE" : [ "危险" , "直接拨打电话" , "允许应用程序直接拨打电话。恶意程序会在用户未知的情况下拨打电话造成损失。但不被允许拨打紧急电话。" ],
		"RECEIVE_SMS" : [ "危险" , "接收短信" , "允许应用程序接收短信。 恶意程序会在用户未知的情况下监视或删除。" ],
		"RECEIVE_MMS" : [ "危险" , "接收MMS" , "允许应用程序接收 MMS 。 恶意程序会在用户未知的情况下监视或删除。" ],
		"READ_SMS" : [ "危险" , "读取短信" , "允许应用程序读取已存储的短信。 恶意程序可能读取保密信息。" ],
		"WRITE_SMS" : [ "危险" , "编辑短信" , "允许应用程序 写入已存储的短信。 恶意程序可能会删除短信。" ],
		"RECEIVE_WAP_PUSH" : [ "危险" , "接收WAP" , "允许应用程序接收 WAP 信息。 恶意程序会在用户未知的情况下监视或删除。" ],
		"READ_CONTACTS" : [ "危险" , "读取联系人信息" , "允许应用程序读取联系人信息。 恶意程序 可以发送你的信息给其他人。" ],
		"WRITE_CONTACTS" : [ "危险" , "写入联系人信息" , "允许应用程序修改联系人信息。 恶意程序会在用户未知的情况下修改或删除。" ],
    "READ_PROFILE" : [ "危险", "读取用户资料", "允许应用程序读取用户个人信息。"],
    "WRITE_PROFILE" : [ "危险", "写入用户资料", "允许应用程序 读写用户个人信息。"],
    "READ_SOCIAL_STREAM" : [ "危险", "读取用户社会流", "允许应用程序读取用户社会流。" ],
    "WRITE_SOCIAL_STREAM" : [ "危险", "写入用户社会流", "允许应用程序读写用户社会流。" ],
    "READ_CALENDAR" : [ "危险" , "读取日历" , "允许应用程序 读取日历。 恶意程序获取你日历中的事件。" ],

		"WRITE_CALENDAR" : [ "危险" , "读写日历" , "允许应用程序读写日历中的事件。" ],
		"READ_USER_DICTIONARY" : [ "危险" , "读取用户的字典" , "允许应用程序读取用户可能已经存储在用户词典中的任何私有字词，名称和短语。" ],
		"WRITE_USER_DICTIONARY" : [ "普通" , "写入用户的字典" , "允许应用程序写入新的词用户词典" ],
		"READ_HISTORY_BOOKMARKS" : [ "危险" , "读取浏览器中的个人信息" , "允许应用程序读取历史纪录和书签。" ],
		"WRITE_HISTORY_BOOKMARKS" : [ "危险" , "写入浏览器中的个人信息" , "允许应用程序读写或删除历史纪录和书签。 恶意程序可以借此清除或修改浏览器的数据。" ],
		"SET_ALARM" : [ "普通" , "设置闹钟" , "允许应用程序在安装的闹钟应用程序中设置闹钟，某些闹钟应用可能无法实现此功能。" ],
		"ACCESS_FINE_LOCATION" : [ "危险" , "定位" , "访问精准的位置源，例如手机上的全球定位系统（如有）。恶意程序可以用它来确定您所在的位置，并可能消耗额外的电池电量。" ],
		"ACCESS_COARSE_LOCATION" : [ "危险" , "获得大致位置" , "访问粗略的位置信息源，如蜂窝网络数据库，以确定手机的大体位置（如果有）。恶意程序可以用它来确定您的大概位置。" ],
		"ACCESS_MOCK_LOCATION" : [ "危险" , "修改gps" , "创建用于测试的模拟位置信息源。恶意程序可以用它来覆盖真实位置信息源。" ],
		"ACCESS_LOCATION_EXTRA_COMMANDS" : [ "普通" , "访问位置提供商" , "访问额外的位置信息提供程序。恶意程序可以以此造成干扰。" ],
		"INSTALL_LOCATION_PROVIDER" : [ "签名(系统)" , "安装位置提供商" , "创建用于测试的模拟位置信息源。恶意程序可以用它来覆盖由真实位置信息源，如GPS或网络提供商返回的位置或状态，或者监视和报告您的位置到外部源" ],
		"INTERNET" : [ "危险" , "创建网络套接字" , "允许应用程序创建网络套接字" ],
		"ACCESS_NETWORK_STATE" : [ "普通" , "查看网络状态" , "允许应用程序查看所有网络的状态。" ],
		"ACCESS_WIFI_STATE" : [ "普通" , "查看Wi-Fi状态" , "允许应用程序查看有关Wi-Fi状态的信息。" ],
		"BLUETOOTH" : [ "危险" , "创建蓝牙连接" , "允许应用程序查看或创建蓝牙连接。" ],
		"NFC" : [ "危险" , "控制nfc功能" , "允许应用程序与支持nfc的物体交互。" ],
		"USE_SIP" : [ "危险" , "收听/发出网络电话" , "允许应用程序使用SIP服务拨打接听互联网通话。" ],
		"ACCOUNT_MANAGER" : [ "签名" , "AMS" , "允许应用程序访问帐户验证器（ams）" ],
		"GET_ACCOUNTS" : [ "普通" , "探索已知账号" , "允许应用程序访问手机已知的帐户列表。" ],
		"AUTHENTICATE_ACCOUNTS" : [ "危险" , "成为凭证验证者" , "允许应用程序获得账户验证权限，能够创建帐户以及获取和设置其密码。" ],
		"USE_CREDENTIALS" : [ "危险" , "使用凭证" , "允许应用程序请求身份验证令牌。" ],
		"MANAGE_ACCOUNTS" : [ "危险" , "管理账号" , "允许应用程序执行操作如添加和删除帐户及删除其密码。" ],
		"MODIFY_AUDIO_SETTINGS" : [ "危险" , "改变音频设置" , "允许应用程序修改全局音频设置，如音量。" ],
		"RECORD_AUDIO" : [ "危险" , "录制音频" , "允许应用程序访问录音路径" ],
		"CAMERA" : [ "危险" , "拍摄" , "允许应用程序拍摄照片和视频，且允许应用程序收集相机在任何时候拍到的图像。" ],
		"VIBRATE" : [ "普通" , "控制震动 " , "允许应用程序控制振动器。" ],
		"FLASHLIGHT" : [ "普通" , "控制闪光灯" , "允许应用程序控制闪光灯。" ],
		"ACCESS_USB" : [ "签名(系统)" , "访问usb" , "允许应用程序访问USB设备。" ],
		"HARDWARE_TEST" : [ "签名" , "测试硬件" , "允许应用程序控制各种外围设备以达到硬件测试的目的。" ],
		"PROCESS_OUTGOING_CALLS" : [ "危险" , "拦截通话" , "允许应用程序处理外拨电话以及更改要拨打的号码。恶意程序可以监视，重定向或阻止电话。" ],
		"MODIFY_PHONE_STATE" : [ "签名(系统)" , "改变手机状态" , "允许应用程序控制设备的电话功能" ],
		"READ_PHONE_STATE" : [ "危险" , "read phone state and identity" , "允许应用程序访问设备的电话功能。拥有此权限的应用程序可确定此手机的电话号码和序列号，是否正在通话中等" ],
		"WRITE_EXTERNAL_STORAGE" : [ "危险" , "读取/修改sd卡内容" , "允许应用程序写入SD卡。" ],
                "READ_EXTERNAL_STORAGE" : ["危险", "读取sd卡内容","允许应用程序从SD卡读取信息。"],
		"WRITE_SETTINGS" : [ "危险" , "改变系统设置" , "允许应用程序修改系统的配置数据。恶意程序可能会损坏系统的配置。" ],
		"WRITE_SECURE_SETTINGS" : [ "签名(系统)" , "改变内部系统设置" , "允许应用程序修改系统的安全设置数据" ],
		"WRITE_GSERVICES" : [ "签名(系统)" , "改变谷歌地图服务" , "允许应用程序修改谷歌地图服务" ],
		"EXPAND_STATUS_BAR" : [ "普通" , "收起/弹出任务条" , "允许应用程序展开或折叠状态条。" ],
		"GET_TASKS" : [ "危险" , "检索运行app" , "允许应用程序检索有关当前和最近运行的任务的信息。可能允许恶意程序发现有关其他应用的私密信息。" ],
		"REORDER_TASKS" : [ "危险" , "安排运行app" , "允许应用程序移动到任务的前景和背景。" ],
		"CHANGE_CONFIGURATION" : [ "危险" , "改变ui设置" , "允许应用程序 允许应用程序更改当前配置，例如语言区域或整体的字体大小。" ],
		"RESTART_PACKAGES" : [ "普通" , "重启进程" , "允许应用程序结束其他应用程序的进程" ],
		"KILL_BACKGROUND_PROCESSES" : [ "普通" , "结束进程" , "允许应用程序结束其他应用程序的后台进程。" ],
		"FORCE_STOP_PACKAGES" : [ "签名" , "强制结束进程" , "允许应用程序强行停止其他应用程序。" ],
		"DUMP" : [ "签名(系统)" , "获得系统内部状态" , "允许应用程序检索系统的内部状态。恶意程序可以获取各种各样的安全信息。" ],
		"SYSTEM_ALERT_WINDOW" : [ "危险" , "弹窗" , "允许应用程序弹窗。 恶意程序可以接管手机的整个屏幕" ],
		"SET_ANIMATION_SCALE" : [ "危险" , "改变速率" , "允许应用程序随时更改全局动画速度。" ],
		"PERSISTENT_ACTIVITY" : [ "危险" , "保持运行" , "允许应用程序持续运转。" ],
		"GET_PACKAGE_SIZE" : [ "普通" , "测量应用程序空间" , "允许应用程序检索其代码，数据和缓存大小。" ],
		"SET_PREFERRED_APPLICATIONS" : [ "签名" , "设置偏好" , "允许应用程序修改您的首选应用程序，这可以允许恶意程序可能会暗中更改运行的应用程序。" ],
		"RECEIVE_BOOT_COMPLETED" : [ "普通" , "开机自启" , "允许应用程序 允许应用程序一旦系统完成启动自行启动，这可能会延长手机的启动时间。" ],
		"BROADCAST_STICKY" : [ "普通" , "发送广播" , "允许应用程序发送广播。" ],
		"WAKE_LOCK" : [ "危险" , "防止手机休眠" , "允许应用程序防止手机休眠。" ],
		"SET_WALLPAPER" : [ "普通" , "设置壁纸" , "允许应用程序设置壁纸。" ],
		"SET_WALLPAPER_HINTS" : [ "普通" , "设置壁纸大小" , "允许应用程序设置壁纸大小。" ],
		"SET_TIME" : [ "签名(系统)" , "设置时间" , "允许应用程序设置时间。" ],
		"SET_TIME_ZONE" : [ "危险" , "设置时区" , "允许应用程序设置时区。" ],
		"MOUNT_UNMOUNT_FILESYSTEMS" : [ "危险" , "镶入文件系统" , "允许应用程序镶入文件系统。" ],
		"MOUNT_FORMAT_FILESYSTEMS" : [ "危险" , "格式化" , "允许应用程序格式化。" ],
		"ASEC_ACCESS" : [ "签名" , "获取内部储存信息" , "允许应用程序获取内部储存信息。" ],
		"ASEC_CREATE" : [ "签名" , "创建内部储存" , "允许应用程序创建内部储存。" ],
		"ASEC_DESTROY" : [ "签名" , "销毁内部储存" , "允许应用程序销毁内部储存。" ],
		"ASEC_MOUNT_UNMOUNT" : [ "签名" , "格式化内部储存" , "允许应用程序格式化内部储存。" ],
		"ASEC_RENAME" : [ "签名" , "重命名内部储存" , "允许应用程序重命名内部储存。" ],
		"DISABLE_KEYGUARD" : [ "危险" , "关闭钥匙锁" , "允许应用程序关闭钥匙锁。" ],
		"READ_SYNC_SETTINGS" : [ "普通" , "读取同步设置" , "允许应用程序读取同步设置。" ],
		"WRITE_SYNC_SETTINGS" : [ "危险" , "修改同步设置" , "允许应用程序修改同步设置。" ],
		"READ_SYNC_STATS" : [ "普通" , "读取同步日志" , "允许应用程序读取同步日志。" ],
		"WRITE_APN_SETTINGS" : [ "危险" , "写入访问点名称设置" , "允许应用程序写入访问点名称设置。" ],
		"SUBSCRIBED_FEEDS_READ" : [ "普通" , "读取订阅信息" , "允许应用程序读取订阅信息。" ],
		"SUBSCRIBED_FEEDS_WRITE" : [ "危险" , "读取订阅信息" , "允许应用程序读取订阅信息。" ],
		"CHANGE_NETWORK_STATE" : [ "危险" , "改变网络连通性" , "允许应用程序改变网络连通性。" ],
		"CHANGE_WIFI_STATE" : [ "危险" , "改变Wi-Fi状态" , "允许应用程序改变Wi-Fi状态。" ],
		"CHANGE_WIFI_MULTICAST_STATE" : [ "危险" , "允许Wi-Fi多播接收" , "允许应用程序允许Wi-Fi多播接收。" ],
		"BLUETOOTH_ADMIN" : [ "危险" , "管理蓝牙" , "允许应用程序管理蓝牙。" ],
		"CLEAR_APP_CACHE" : [ "危险" , "删除所有临时文件" , "允许应用程序删除所有临时文件。" ],
		"READ_LOGS" : [ "危险" , "读取敏感日志" , "允许应用程序读取系统日志。 " ],
		"SET_DEBUG_APP" : [ "危险" , "开启调试" , "允许应用程序调试其他应用程序。恶意程序可以用它来结束其他应用程序。" ],
		"SET_PROCESS_LIMIT" : [ "危险" , "限制进程数量" , "允许应用程序限制进程数量" ],
		"SET_ALWAYS_FINISH" : [ "危险" , "关闭所有后台应用" , "允许应用程序控制所有后台应用" ],
		"SIGNAL_PERSISTENT_PROCESSES" : [ "危险" , "发送Linux信号" , "允许应用程序发送Linux的信号" ],
		"DIAGNOSTIC" : [ "签名" , "读写所有的诊断资源" , "允许应用程序读写诊断组的任何资源" ],
		"STATUS_BAR" : [ "签名(系统)" , "修改/禁止状态条" , "允许应用程序 用状态条" ],
		"STATUS_BAR_SERVICE" : [ "签名" , "状态条" , "允许应用程序加入状态条。" ],
		"FORCE_BACK" : [ "签名" , "强制关闭" , "允许应用程序强制任何前台程序关闭。" ],
		"UPDATE_DEVICE_STATS" : [ "签名(系统)" , "改变电源统计信息" , "允许改变电源统计信息" ],
		"INTERNAL_SYSTEM_WINDOW" : [ "签名" , "显示未认证窗口" , "允许显示未认证的窗口。" ],
		"MANAGE_APP_TOKENS" : [ "签名" , "管理应用凭证" , "允许应用创建和管理凭证。" ],
		"INJECT_EVENTS" : [ "签名" , "控制按钮" , "允许应用程序修改对其他应用程序的输入。 恶意程序可用此接管设备" ],
		"SET_ACTIVITY_WATCHER" : [ "签名" , "监视/控制所有应用的开启" , "允许应用程序监视和控制应用启动方式。 恶意程序会破坏整个系统。" ],
		"SHUTDOWN" : [ "签名" , "部分关闭" , "使活动管理器进入关机状态。" ],
		"STOP_APP_SWITCHES" : [ "签名" , "防止应用转换" , "防止用户切换至另一个应用程序。" ],
		"READ_INPUT_STATE" : [ "签名" , "录制动作" , "允许应用程序录制屏幕上的动作。" ],
		"BIND_INPUT_METHOD" : [ "签名" , "绑定到输入法" , "允许绑定到输入法的顶级接口" ],
		"BIND_WALLPAPER" : [ "签名(系统)" , "绑定到壁纸" , "允许绑定到壁纸" ],
		"BIND_DEVICE_ADMIN" : [ "签名" , "与用户交互" , "允许手机用户将意向发送到设备管理" ],
		"SET_ORIENTATION" : [ "签名" , "更改屏幕方向" , "允许应用程序更改屏幕的旋转。" ],
		"INSTALL_PACKAGES" : [ "签名(系统)" , "直接安装应用" , "允许应用程序安装或更新包。 恶意程序可以用此添加权限。" ],
		"CLEAR_APP_USER_DATA" : [ "签名" , "删除应用/数据" , "允许应用程序清除用户数据。" ],
		"DELETE_CACHE_FILES" : [ "签名(系统)" , "删除其他应用临时文件" , "允许应用程序删除临时文件。" ],
		"DELETE_PACKAGES" : [ "签名(系统)" , "删除应用程序" , "允许应用程序删除包。 恶意程序可以用它来删除重要的应用。" ],
		"MOVE_PACKAGE" : [ "签名(系统)" , "移动应用程序资源" , "允许应用程序移动内部应用程序资源到外部媒体" ],
		"CHANGE_COMPONENT_ENABLED_STATE" : [ "签名(系统)" , "启用或禁用应用程序组件" , "允许应用程序开启其他应用程序的组件" ],
		"ACCESS_SURFACE_FLINGER" : [ "签名" , "访问SurfaceFlinger" , "允许应用程序使用SurfaceFlinger低级别功能。" ],
		"READ_FRAME_BUFFER" : [ "签名" , "读取帧缓冲区" , "允许应用程序读取缓冲区的内容。" ],
		"BRICK" : [ "签名" , "永久禁用手机" , "允许应用程序永久停用整个手机" ],
		"REBOOT" : [ "签名(系统)" , "强制重启" , "允许应用程序强制系统重启。" ],
		"DEVICE_POWER" : [ "签名" , "打开或关闭设备" , "允许应用程序启动/关闭设备。" ],
		"FACTORY_TEST" : [ "签名" , "在ftm中运行" , "进行低级别制造商测试，允许对手机硬件进行完全访问。" ],
		"BROADCAST_PACKAGE_REMOVED" : [ "签名" , "发送溢出包的广播" , "允许应用程序广播一个应用程序包已经移除的通知。恶意程序可能借此终止其他应用程序的运行。" ],
		"BROADCAST_SMS" : [ "签名" , "发送短信接收广播" , "允许应用程序 允许应用程序广播一条短信已收到通知。恶意程序可能会借此伪造收到的短信。" ],
		"BROADCAST_WAP_PUSH" : [ "签名" , "发送wpr广播" , "允许应用程序广播一个WAP-PUSH消息" ],
		"MASTER_CLEAR" : [ "签名(系统)" , "恢复系统至出场模式" , "允许应用程序将系统完全重置为出厂设置。" ],
		"CALL_PRIVILEGED" : [ "签名(系统)" , "直接拨打任何电话号码" , "允许应用程序允许应用程序拨打任何电话号码，包括紧急号码。" ],
		"PERFORM_CDMA_PROVISIONING" : [ "签名(系统)" , "直接启动CDMA手机设置" , "允许应用程序启动CDMA服务。" ],
		"CONTROL_LOCATION_UPDATES" : [ "签名(系统)" , "控制位置更新通知" , "" ],
		"ACCESS_CHECKIN_PROPERTIES" : [ "签名(系统)" , "访问check-in的属性" , "" ],
		"PACKAGE_USAGE_STATS" : [ "签名" , "更新组件使用统计" , "允许修改组件使用情况统计" ],
		"BATTERY_STATS" : [ "普通" , "修改电池统计" , "允许对手机电池统计信息进行修改" ],
		"BACKUP" : [ "签名(系统)" , "控制系统备份和恢复" , "允许应用程序系统备份和恢复" ],
		"BIND_APPWIDGET" : [ "签名(系统)" , "选择部件" , "" ],
		"CHANGE_BACKGROUND_DATA_SETTING" : [ "签名" , "change background data usage setting" , "允许应用程序更改后台数据使用设置" ],
		"GLOBAL_SEARCH" : [ "签名(系统)" , "" , "" ],
		"GLOBAL_SEARCH_CONTROL" : [ "签名" , "" , "" ],
		"SET_WALLPAPER_COMPONENT" : [ "签名(系统)" , "" , "" ],
		"ACCESS_CACHE_FILESYSTEM" : [ "签名(系统)" , "访问临时文件系统" , "允许应用程序读写缓存文件系统。" ],
		"COPY_PROTECTED_DATA" : [ "签名" , "Allows to invoke default container service to copy content。" , "Allows to invoke default container service to copy content。" ],
		"C2D_MESSAGE" : [ "签名" , "允许云端通讯" , "允许应用程序接收推送通知。" ],
    
    "ADD_VOICEMAIL" : [ "危险", "添加语音邮件", "允许应用程序 add voicemails into the system。" ],
    },

    "MANIFEST_PERMISSION_GROUP" : 
        {

        "ACCOUNTS" : "Permissions for direct access to the accounts managed by the Account Manager。",
        "COST_MONEY" : "Used for permissions that can be used to make the user spend money without their direct involvement。",
        "DEVELOPMENT_TOOLS" : "Group of permissions that are related to development features。",
        "HARDWARE_CONTROLS" : "Used for permissions that provide direct access to the hardware on the device。",
        "LOCATION" : "Used for permissions that allow access to the user's current location。",
        "MESSAGES" : "Used for permissions that allow an application to send messages on behalf of the user or intercept messages being received by the user。",
        "NETWORK" : "Used for permissions that provide access to networking services。",
        "PERSONAL_INFO" : "Used for permissions that provide access to the user's private data, such as contacts, calendar events, e-mail messages, etc。",
        "PHONE_CALLS" : "Used for permissions that are associated with accessing and modifyign telephony state: intercepting outgoing calls, reading and modifying the phone state。",
        "STORAGE" : "Group of permissions that are related to SD card access。",
        "SYSTEM_TOOLS" : "Group of permissions that are related to system APIs。",
    },
}
